### ISSUE TITLE
clientDeferred.catch is not a function

### ISSUE THREAD

**Issue by ivolimasilva** [moxystudio/next-intl#12]
The latest version (`v2.0.1`) introduced a bug by calling `catch` from the result of [`p-defer`](https://github.com/sindresorhus/p-defer).

 https://github.com/moxystudio/next-intl/blob/4e39c5ea091b0110360b8e85e6a1e7f2c169c277/src/plugin/NextIntlWebpackPlugin.js#L27

This results in the following error:

```
TypeError: NextIntlWebpackPlugin.clientDeferred.catch is not a function
    at NextIntlWebpackPlugin.apply (<DIR>/next-with-moxy/node_modules/@moxy/next-intl/lib/plugin/NextIntlWebpackPlugin.js:41:49)
    at webpack (<DIR>/next-with-moxy/node_modules/webpack/lib/webpack.js:51:13)
    at <DIR>/next-with-moxy/node_modules/webpack/lib/webpack.js:36:39
    at Array.map (<anonymous>)
    at webpack (<DIR>/next-with-moxy/node_modules/webpack/lib/webpack.js:36:24)
    at HotReloader.start (<DIR>/next-with-moxy/node_modules/next/dist/server/hot-reloader.js:14:1858)
    at async DevServer.prepare (<DIR>/next-with-moxy/node_modules/next/dist/server/next-dev-server.js:6:1541)
    at async <DIR>/next-with-moxy/node_modules/next/dist/cli/next-dev.js:22:359
```

I don't know what bug you were trying to solve by adding that line, but wasn't it supposed to be `.promise.catch(...`?

```js
NextIntlWebpackPlugin.clientDeferred.promise.catch(() => {});
```

If so, let me know and I'll do the PR :smile:

**Comment by satazor** [comment]
Nice catch. I guess this was fixed in some recent version, so I’m going to close this.
